# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
        exclude: ".*json$|.*txt$|.*csv|.*md"
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-ast
      - id: end-of-file-fixer
      - id: check-added-large-files

#  - repo: https://github.com/pre-commit/mirrors-prettier
#    rev: v2.2.1
#    hooks:
#      - id: prettier
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: python
        types:
          - python
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types:
          - python
      - id: black
        name: black
        entry: black
        language: python
        language_version: python3.9
        types:
          - python
files: '.*'
